sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

install:
  - npm install

script:
  - tsc index.ts
  - docker build -t qinling/jenkinsassistant:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push qinling/jenkinsassistant:latest